"use client";
// import type { Metadata } from "next";
import Nav from "@/components/Nav";
import { usePathname, useRouter } from "next/navigation";
import AppProvider from "@/context/AppContext";

import "./globals.css";
import { useEffect } from "react";
import useAuth from "@/hooks/useFirebase";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const { user, loading } = useAuth();
  const pathname = usePathname();
  const hideNav = pathname === "/login";

  useEffect(() => {
    if (user === undefined || loading) return;
    if (user === null) {
      router.push("/login");
    }
  }, [loading, router, user]);

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AppProvider>
          <>
            {!hideNav && <Nav />}
            {children}
          </>
        </AppProvider>
      </body>
    </html>
  );
}
